import { PermissionName } from '../enum/permission-name.enum';
import { BooleanType } from '../enum/boolean-type.enum';

export const permissionObject = [
  {
    permission: PermissionName.SUPER_ADMIN,
    description: 'Super Admin Permission',
    groupList: BooleanType.True,
    groupAdd: BooleanType.True,
    groupEdit: BooleanType.True,
    groupDelete: BooleanType.True,
    permissionList: BooleanType.True,
    permissionAdd: BooleanType.True,
    permissionEdit: BooleanType.True,
    permissionDelete: BooleanType.True,
    userList: BooleanType.True,
    userAdd: BooleanType.True,
    userEdit: BooleanType.True,
    userDelete: BooleanType.True,
    categoryList: BooleanType.True,
    categoryAdd: BooleanType.True,
    categoryEdit: BooleanType.True,
    categoryDelete: BooleanType.True,
    productList: BooleanType.True,
    productAdd: BooleanType.True,
    productEdit: BooleanType.True,
    productDelete: BooleanType.True,
    orderList: BooleanType.True,
    orderAdd: BooleanType.True,
    orderEdit: BooleanType.True,
    orderDelete: BooleanType.True,
  },
  {
    permission: PermissionName.ADMIN,
    description: 'Admin Permission',
    groupList: BooleanType.False,
    groupAdd: BooleanType.False,
    groupEdit: BooleanType.False,
    groupDelete: BooleanType.False,
    permissionList: BooleanType.False,
    permissionAdd: BooleanType.False,
    permissionEdit: BooleanType.False,
    permissionDelete: BooleanType.False,
    userList: BooleanType.True,
    userAdd: BooleanType.True,
    userEdit: BooleanType.True,
    userDelete: BooleanType.True,
    categoryList: BooleanType.True,
    categoryAdd: BooleanType.True,
    categoryEdit: BooleanType.True,
    categoryDelete: BooleanType.True,
    productList: BooleanType.True,
    productAdd: BooleanType.True,
    productEdit: BooleanType.True,
    productDelete: BooleanType.True,
    orderList: BooleanType.True,
    orderAdd: BooleanType.True,
    orderEdit: BooleanType.True,
    orderDelete: BooleanType.True,
  },
  {
    permission: PermissionName.MANAGEMENT,
    description: 'Management Permission',
    groupList: BooleanType.False,
    groupAdd: BooleanType.False,
    groupEdit: BooleanType.False,
    groupDelete: BooleanType.False,
    permissionList: BooleanType.False,
    permissionAdd: BooleanType.False,
    permissionEdit: BooleanType.False,
    permissionDelete: BooleanType.False,
    userList: BooleanType.True,
    userAdd: BooleanType.True,
    userEdit: BooleanType.True,
    userDelete: BooleanType.True,
    categoryList: BooleanType.True,
    categoryAdd: BooleanType.True,
    categoryEdit: BooleanType.True,
    categoryDelete: BooleanType.True,
    productList: BooleanType.True,
    productAdd: BooleanType.True,
    productEdit: BooleanType.True,
    productDelete: BooleanType.True,
    orderList: BooleanType.True,
    orderAdd: BooleanType.True,
    orderEdit: BooleanType.True,
    orderDelete: BooleanType.True,
  },
  {
    permission: PermissionName.SELLER,
    description: 'Seller Permission',
    groupList: BooleanType.False,
    groupAdd: BooleanType.False,
    groupEdit: BooleanType.False,
    groupDelete: BooleanType.False,
    permissionList: BooleanType.False,
    permissionAdd: BooleanType.False,
    permissionEdit: BooleanType.False,
    permissionDelete: BooleanType.False,
    userList: BooleanType.False,
    userAdd: BooleanType.False,
    userEdit: BooleanType.False,
    userDelete: BooleanType.False,
    categoryList: BooleanType.False,
    categoryAdd: BooleanType.False,
    categoryEdit: BooleanType.False,
    categoryDelete: BooleanType.False,
    productList: BooleanType.True,
    productAdd: BooleanType.True,
    productEdit: BooleanType.True,
    productDelete: BooleanType.True,
    orderList: BooleanType.True,
    orderAdd: BooleanType.True,
    orderEdit: BooleanType.True,
    orderDelete: BooleanType.True,
  },
  {
    permission: PermissionName.DELIVERY,
    description: 'Delivery Permission',
    groupList: BooleanType.False,
    groupAdd: BooleanType.False,
    groupEdit: BooleanType.False,
    groupDelete: BooleanType.False,
    permissionList: BooleanType.False,
    permissionAdd: BooleanType.False,
    permissionEdit: BooleanType.False,
    permissionDelete: BooleanType.False,
    userList: BooleanType.False,
    userAdd: BooleanType.False,
    userEdit: BooleanType.False,
    userDelete: BooleanType.False,
    categoryList: BooleanType.False,
    categoryAdd: BooleanType.False,
    categoryEdit: BooleanType.False,
    categoryDelete: BooleanType.False,
    productList: BooleanType.False,
    productAdd: BooleanType.False,
    productEdit: BooleanType.False,
    productDelete: BooleanType.False,
    orderList: BooleanType.True,
    orderAdd: BooleanType.False,
    orderEdit: BooleanType.True,
    orderDelete: BooleanType.False,
  },
  {
    permission: PermissionName.CUSTOMER,
    description: 'Customer Permission',
    groupList: BooleanType.False,
    groupAdd: BooleanType.False,
    groupEdit: BooleanType.False,
    groupDelete: BooleanType.False,
    permissionList: BooleanType.False,
    permissionAdd: BooleanType.False,
    permissionEdit: BooleanType.False,
    permissionDelete: BooleanType.False,
    userList: BooleanType.False,
    userAdd: BooleanType.False,
    userEdit: BooleanType.False,
    userDelete: BooleanType.False,
    categoryList: BooleanType.False,
    categoryAdd: BooleanType.False,
    categoryEdit: BooleanType.False,
    categoryDelete: BooleanType.False,
    productList: BooleanType.True,
    productAdd: BooleanType.False,
    productEdit: BooleanType.False,
    productDelete: BooleanType.False,
    orderList: BooleanType.True,
    orderAdd: BooleanType.True,
    orderEdit: BooleanType.False,
    orderDelete: BooleanType.False,
  },
];
