export enum OrderStatusName {
  ORDERED = 'ORDERED',
  PROCESSING = 'PROCESSING',
  PACKAGING = 'PACKAGING',
  HANDED_TO_DELIVERY_TEAM = 'HANDED_TO_DELIVERY_TEAM',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
}
